### PR TITLE
change environment key to api_url key

### LINKED ISSUE #4: Getting 401 Error when using this provider
Hey, this provider seems brand new, so a question before: Is it already stable? If not, just ignore this issue :).

# Bug

```
│ Error: Error creating service
│ 
│   with clickhouse_service.this,
│   on main.tf line 18, in resource "clickhouse_service" "this":
│   18: resource "clickhouse_service" "this" {
│ 
│ Could not create service, unexpected error: status: 401, body: {"error":"UNAUTHORIZED: Key is not found","status":401}
```

The weird thing is, when I use the credentials of the provider that I have created on clickhouse.cloud with the following curl, I get a `200 OK` response.

```sh
curl --silent --user $KEY:$SECRET https://api.clickhouse.cloud/v1/organizations
```

# Reproduction

I went to `clickhouse.cloud > API Keys > + New API Key`, created it and pasted the outputs to the following file.

```terraform
# main.tf
terraform {
  required_providers {
    clickhouse = {
      source  = "ClickHouse/clickhouse"
      version = "~> 0.0.2"
    }
  }
}

provider "clickhouse" {
  environment     = "staging"
  organization_id = "<org_id>"
  token_key       = "<token_key>"
  token_secret    = "<token_secret>"
}

resource "clickhouse_service" "this" {
  cloud_provider       = "aws"
  region               = var.aws_region
  name                 = "staging-service"
  tier                 = var.tier
  idle_scaling         = var.idle_scaling
  idle_timeout_minutes = var.idle_timeout_minutes
  min_total_memory_gb  = var.min_total_memory_gb
  max_total_memory_gb  = var.max_total_memory_gb
  password             = random_password.this.result
  ip_access            = [    
    {
        source      = "92.168.2.63"
        description = "Test IP"
    }
  ]
}

resource "random_password" "this" {
  length  = 32
  special = false
}
```

### PR DESCRIPTION
**Pull request by Kinzeng**
fixes #4

### CODE REVIEW

File: clickhouse/provider.go [hunk 1]
```diff
@@ -126,13 +125,15 @@ func (p *clickhouseProvider) Configure(ctx context.Context, req provider.Configu
...
 	tokenKey := os.Getenv("CLICKHOUSE_TOKEN_KEY")
 	tokenSecret := os.Getenv("CLICKHOUSE_TOKEN_KEY")
 
-	if !config.Environment.IsNull() {
-		environment = config.Environment.ValueString()
+	if !config.ApiUrl.IsNull() {
+		apiUrl = config.ApiUrl.ValueString()
+	} else {
+		apiUrl = "https://api.clickhouse.cloud/v1"
 	}
```
Comment (jkaflik) [inline clickhouse/provider.go:137]: If a URL is not provided in the provider config and I want to use env var, it will be overridden with line 136 anyway.

File: clickhouse/provider.go [hunk 2]
```diff
@@ -150,26 +151,16 @@ func (p *clickhouseProvider) Configure(ctx context.Context, req provider.Configu
...
 		resp.Diagnostics.AddAttributeError(
-			path.Root("environment"),
-			"Missing ClickHouse OpenAPI Environment",
+			path.Root("api_url"),
+			"Missing ClickHouse OpenAPI API URL",
 			"The provider cannot create the ClickHouse OpenAPI client: missing or empty value for the environment. "+
 				"Set the environment value in the configuration or use the CLICKHOUSE_ENV environment variable. "+
 				"If either is already set, ensure the value is not empty.",
 		)
 	}
```
Comment (jkaflik) [inline clickhouse/provider.go:162]: This is likely not to happen due to the logic in the previous lines. Anyway, we should fix error message:

```
	if apiUrl == "" {
		resp.Diagnostics.AddAttributeError(
			path.Root("api_url"),
			"Missing ClickHouse OpenAPI API URL",
			"The provider cannot create the ClickHouse OpenAPI client: missing or empty value for the API url. "+
				"Set the API url value in the configuration or use the CLICKHOUSE_API_URL environment variable. "+
				"If either is already set, ensure the value is not empty.",
		)
	}
	```

File: docs/index.md [hunk 3]
```diff
@@ -34,4 +34,4 @@ provider "clickhouse" {
 
 ### Optional
 
-- `environment` (String) Deployment environment of the OpenAPI the provider will interact with.
+- `api_url` (String) API URL of the ClickHouse OpenAPI the provider will interact with. Only specify if you have a specific deployment of the ClickHouse OpenAPI you want to run against.
```
Comment (jkaflik) [inline docs/index.md:37]: Do you think we should mention this optional at all?

**Review by jkaflik — CHANGES_REQUESTED** [review]

File: docs/index.md (hunk 3 above)
Comment (Kinzeng) [reply docs/index.md:37]: yeah we can just hide it for now

**Review by jkaflik — APPROVED** [review]
